Repository MykytaKyt/datakyt, pull requests merged in 2020-11, with the labels that each got.

#27 Added qr generator demo
  examples/qr-generator-demo/qr-generator-demo.py
  examples/qr-generator-demo/test_data.csv
Labels: priority: high

#30 Fix mistakes in docs for db
  README.md
  docs/database.drawio
  docs/diagram.md
  docs/images/database.png
Labels: priority: medium

#28 add create_database.sql and create_table.sql files
  README.md
  datakyt/db/create_database.sql
  datakyt/db/create_table.sql
Labels: priority: high

#32 Add _config.py for global config
  datakyt/_config.py
Labels: type: good first issue

#33 Added a method to write a name to qrcode [#29]
  examples/qr-generator-demo/qr-generator-demo.py
Labels: priority: medium

#36 Add requirements.txt
  requirements.txt
Labels: priority: high

#31 Create pg_dump for data base
  datakyt/db/create_table.sql
  datakyt/db/dump_db.py
Labels: type: good first issue
